# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a54x/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),a54x)

$(call add-radio-file-sha1-checked,radio/modem.bin,7b9d62af6d2cfb4a193bc5271264d41f80ee98b4)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin,d1861fb2bfe1f78f8d42c610980c09d64a91e029)

endif
